env:
    CONAN_REMOTES: "https://barbarian.bfgroup.xyz/github@True@barbarian-github"
    CONAN_BUILD_POLICY: "missing"
    BPT_NO_UPLOAD: yes
    BPT_CONFIG_FILE_VERSION: "11"

on:
    push:
        branches: ["main", "develop"]
    pull_request:

name: conan

jobs:
    generate-matrix:
        name: Generate Job Matrix
        runs-on: ubuntu-latest
        outputs:
            matrix: ${{ steps.set-matrix.outputs.matrix }}
        steps:
            - { uses: actions/checkout@v2, with: { fetch-depth: "0" } }
            - { uses: actions/setup-python@v2, with: { python-version: "3.x" } }
            - name: Install Package Tools
              run: |
                  pip install git+https://github.com/bfgroup/bincrafters-package-tools@develop
                  conan user
            - name: Generate Job Matrix
              id: set-matrix
              run: |
                  MATRIX=$(bincrafters-package-tools generate-ci-jobs --platform gha)
                  echo "${MATRIX}"
                  echo "::set-output name=matrix::${MATRIX}"
    conan:
        needs: generate-matrix
        runs-on: ${{ matrix.config.os }}
        strategy:
            fail-fast: false
            matrix: ${{fromJson(needs.generate-matrix.outputs.matrix)}}
        name: ${{ matrix.config.name }}
        steps:
            - { uses: actions/checkout@v2, with: { fetch-depth: "0" } }
            - { uses: actions/setup-python@v2, with: { python-version: "3.x" } }
            - name: Install Conan
              env:
                  BPT_MATRIX: ${{toJson(matrix.config)}}
              run: |
                  pip install git+https://github.com/bfgroup/bincrafters-package-tools@develop
                  # remove newlines from matrix first
                  matrix=$(echo ${BPT_MATRIX})
                  bincrafters-package-tools prepare-env --platform gha --config "${matrix}"
              shell: bash
            - name: Run
              run: |
                  bincrafters-package-tools --auto
